"""Initial models

Revision ID: 103a1360b88b
Revises: 
Create Date: 2025-11-17 20:49:29.351713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103a1360b88b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('lottery_number', sa.String(length=50), nullable=True),
    sa.Column('qr_hash', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('has_won', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_hash')
    )
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_list_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_list_has_won'), ['has_won'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_list_lottery_number'), ['lottery_number'], unique=False)

    op.create_table('drawn_tail_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tail_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drawn_tail_number_tail_number'), ['tail_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawn_tail_number_tail_number'))

    op.drop_table('drawn_tail_number')
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_list_lottery_number'))
        batch_op.drop_index(batch_op.f('ix_checkin_list_has_won'))
        batch_op.drop_index(batch_op.f('ix_checkin_list_employee_id'))

    op.drop_table('checkin_list')
    # ### end Alembic commands ###
