"""Add has_won_public

Revision ID: 3127d9df2348
Revises: 6bd8a0a3be14
Create Date: 2026-01-19 14:48:37.294788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3127d9df2348'
down_revision = '6bd8a0a3be14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_won_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_column('has_won_public')

    # ### end Alembic commands ###
