"""Add site and dept_code

Revision ID: 548fd47c3979
Revises: 95632688a722
Create Date: 2026-01-15 23:52:40.795481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548fd47c3979'
down_revision = '95632688a722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dept_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_column('dept_code')
        batch_op.drop_column('site')

    # ### end Alembic commands ###
