"""Add claim status columns

Revision ID: 553560d56353
Revises: 3127d9df2348
Create Date: 2026-01-19 15:58:39.196047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553560d56353'
down_revision = '3127d9df2348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_claimed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('public_prize_claimed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_column('public_prize_claimed')
        batch_op.drop_column('prize_claimed')

    # ### end Alembic commands ###
