"""add participant_type linked_employee_id meal_type group_name

Revision ID: 651c6c783d29
Revises: 3ef1ac22d66f
Create Date: 2026-05-04 22:12:34.648408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651c6c783d29'
down_revision = '3ef1ac22d66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('linked_employee_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meal_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_column('group_name')
        batch_op.drop_column('meal_type')
        batch_op.drop_column('linked_employee_id')
        batch_op.drop_column('participant_type')

    # ### end Alembic commands ###
