"""Change tail_number to string and add is_addon

Revision ID: 6bd8a0a3be14
Revises: 548fd47c3979
Create Date: 2026-01-19 13:42:38.166516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd8a0a3be14'
down_revision = '548fd47c3979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_addon', sa.Boolean(), nullable=True))
        batch_op.alter_column('tail_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.alter_column('tail_number',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_addon')

    # ### end Alembic commands ###
