"""Add table and biz trip

Revision ID: 90ae38673f7f
Revises: f280626503eb
Create Date: 2026-01-26 22:54:32.025809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ae38673f7f'
down_revision = 'f280626503eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_business_trip', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_list', schema=None) as batch_op:
        batch_op.drop_column('is_business_trip')
        batch_op.drop_column('table_number')

    # ### end Alembic commands ###
