"""Add cancellation log

Revision ID: 95632688a722
Revises: 99e8b46574f7
Create Date: 2026-01-14 23:50:06.842002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95632688a722'
down_revision = '99e8b46574f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_list_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_by', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_list_id'], ['checkin_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancellation_log')
    # ### end Alembic commands ###
