"""Remove unique constraint and add prize_type

Revision ID: f280626503eb
Revises: 553560d56353
Create Date: 2026-01-19 17:15:52.744976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f280626503eb'
down_revision = '553560d56353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prize_type', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_drawn_tail_number_tail_number'))
        batch_op.create_index(batch_op.f('ix_drawn_tail_number_tail_number'), ['tail_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawn_tail_number', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drawn_tail_number_tail_number'))
        batch_op.create_index(batch_op.f('ix_drawn_tail_number_tail_number'), ['tail_number'], unique=True)
        batch_op.drop_column('prize_type')

    # ### end Alembic commands ###
